spring.application.name=catalog-api

server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

jwt.secret=S8d0!92hd13#1d9H@33Gg88eKlaQZx72AjfFg93&kPqLuWmNcZ
jwt.expiration = 86400000

logging.pattern.console=%C{1} [%-5level] %d{HH:mm:ss} - %msg%n

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres


spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
spring.kafka.properties.schema.registry.url=http://localhost:8081

category.created.event.topic.name=category-created-topic

logging.level.org.springframework.security=TRACE

